### ISSUE TITLE
Allow up to 8 colors in garage

### ISSUE THREAD

**Issue by Naworm** [Nahelam/PCSX2-Burnout-Mods#2]
```
// Allow up to 8 colors in garage (SLUS-21050_BEBF8793.ini)
RAW: 2042BCB0 24070008
PNACH: patch=1,EE,2042BCB0,extended,24070008
```

Hello,
I found this patch on https://forum.mattkc.com/viewtopic.php?t=131
I am not sure of what is is supposed to do, but it do not seems to works
Maybe you wanna check =)

**Comment by Nahelam** [comment]
I remember trying it in the past and it was working fine, note that it doesn't work for all vehicles, I have not planned to work on color palettes patches for the moment.
